#ifndef CONFIG_H
#define CONFIG_H

#ifndef ERROR_FORMAT_BUFFER_SIZE
	#define ERROR_FORMAT_BUFFER_SIZE (0x1000ULL)
#endif // ERROR_FORMAT_BUFFER_SIZE

#ifndef INTEGER_FORMAT_BUFFER_SIZE
	#define INTEGER_FORMAT_BUFFER_SIZE (0x100ULL)
#endif // INTEGER_FORMAT_BUFFER_SIZE

#ifndef REAL_FORMAT_BUFFER_SIZE
	#define REAL_FORMAT_BUFFER_SIZE (0x100ULL)
#endif // REAL_FORMAT_BUFFER_SIZE

#ifndef MAP_INITIAL_CAPACITY
	#define MAP_INITIAL_CAPACITY (128ULL)
#endif // MAP_INITIAL_CAPACITY

#ifndef MAP_INITIAL_HASH
	#define MAP_INITIAL_HASH (5381ULL)
#endif // MAP_INITIAL_HASH

#ifndef MAP_LOAD_FACTOR
	#define MAP_LOAD_FACTOR (0.75F)
#endif // MAP_LOAD_FACTOR

#ifndef VECTOR_INITIAL_CAPACITY
	#define VECTOR_INITIAL_CAPACITY (16ULL)
#endif // VECTOR_INITIAL_CAPACITY

#ifndef STRING_INITIAL_CAPACITY
	#define STRING_INITIAL_CAPACITY (16ULL)
#endif // STRING_INITIAL_CAPACITY

#endif // CONFIG_H
